### ISSUE TITLE
Channels cannot instantiate SessionStore object

### ISSUE THREAD

**Issue by pydanny** [Bouke/django-user-sessions#55] opened 2016-04-18 23:16 UTC
I know this is currently unmainted, but filing this here for reference:

Using Django 1.9.5 and Channels 0.11.0, this is the error I get:

```
2016-04-18 15:42:01,756 - ERROR - worker - Error processing message with consumer awesome.discussions.consumers.ws_connect:
Traceback (most recent call last):
  File "/Users/danielgreenfeld/.virtualenvs/awesome/lib/python3.5/site-packages/channels/worker.py", line 78, in run
    consumer(message, **kwargs)
  File "/Users/danielgreenfeld/.virtualenvs/awesome/lib/python3.5/site-packages/channels/sessions.py", line 153, in inner
    session = session_engine.SessionStore(session_key=session_key)
TypeError: __init__() missing 2 required positional arguments: 'user_agent' and 'ip'
```

**Comment by pydanny** [comment] 2016-04-18 23:18
This is because Channels' websockets is bump into https://github.com/Bouke/django-user-sessions/blob/master/user_sessions/middleware.py#L20-L24, where the user_sessions custom user object requires two extra arguments.

**Comment by Bouke** [comment] 2016-09-21 20:58
Hi @pydanny, I missed your issue. Is this issue still relevant, or is it resolved in later versions of Channels? I haven't worked with Channels myself. The middleware provided by this package provides the additional arguments (which is the meat of this package). I'm not sure if/what changes would be needed to get this to work with Channels.

**Comment by pydanny** [comment] 2016-09-21 21:43
This issue isn't relevant anymore. You can close this issue.

**Comment by andrewfam** [comment] 2016-12-04 14:45
Still getting the errors

**Comment by andrewfam** [comment] 2016-12-04 14:46
2016-12-04 22:46:16,399 - ERROR - worker - Error processing message with consumer dpms.consumers.ws_connect:
Traceback (most recent call last):
  File "/Users/andrewfam/.virtualenvs/dpms/lib/python2.7/site-packages/channels/worker.py", line 120, in run
    consumer(message, **kwargs)
  File "/Users/andrewfam/.virtualenvs/dpms/lib/python2.7/site-packages/channels/sessions.py", line 54, in inner
    session = session_for_reply_channel(message.reply_channel.name)
  File "/Users/andrewfam/.virtualenvs/dpms/lib/python2.7/site-packages/channels/sessions.py", line 27, in session_for_reply_channel
    instance = session_engine.SessionStore(session_key=session_key)
TypeError: __init__() takes at least 3 arguments (2 given)

**Comment by andrewfam** [comment] 2016-12-04 23:06
Thanks Bouke for reopenning. Would be happy to work with you on resolving this.

**Comment by Bouke** [comment] 2016-12-05 20:48
The problem is that Channels requires `django.contrib.session` or exact the same API for that matter. This package has a customized `SessionStore` that requires additional arguments, which Channels doesn't know about. So in order to resolve this issue, Channels has to provide some override method for instantiating the `SessionStore`. I'm not familiar with Channels. I would be happy to accept a PR that resolves the issue, however I think that part of the solution is a change in Channels.

**Comment by Bouke** [comment] 2016-12-05 20:55
OTOH the `ip` and `user_agent` arguments could possibly be made optional. Then those variables might not be available, but the sessions would still work.

**Closed** 2016-12-05 22:27 UTC
Labels: enhancement
